### ISSUE TITLE
How to execute generate.py

### ISSUE THREAD

**Issue by victordiao** [WERush/RNN-LSTM#1]
Hi, I find this useful code
But I can't execute it, neither on linux or Mac
Could you tell the dependency, the version?

the error like below:
Traceback (most recent call last):
  File "generate.py", line 90, in <module>
    next_index = sample(preds, diversity)
  File "generate.py", line 66, in sample
    return np.argmax(np.random.multinomial(1,a,1))
  File "mtrand.pyx", line 4815, in mtrand.RandomState.multinomial (numpy/random/mtrand/mtrand.c:36134)
ValueError: sum(pvals[:-1]) > 1.0

THANKS!

**Comment by WERush** [comment]
This code was implemented two years ago. The version of Keras is 1.0.3, and it can also run on my computer (MacOS, cpu-only, python2.7, anaconda and TensorFlow backend). Maybe you can reimplement it by your favourite DL framework and the dataset is in the "poetryFromTang.txt".

Using TensorFlow backend.
opening txt
corpus length: 16647
total chars: 2514
nb sequences: 5536
Vectorization...
Build model...
Modelling finishing
--------------------------------------------------
Iteration 1
Epoch 1/1
1408/5536 [======>.......................] - ETA: 149s - loss: 7.1127
